<a href="https://colab.research.google.com/github/CaseySo/COGS109_FINAL_PROJECT/blob/main/work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [72]:
diabetes = pd.read_sas("DIQ_L.xpt", format="xport")
alcohol = pd.read_sas("ALQ_L.xpt", format="xport")
smoking = pd.read_sas("SMQ_L.xpt", format="xport")
demographics = pd.read_sas("DEMO_L.xpt", format="xport")
physical_activity = pd.read_sas("PAQ_L.xpt", format="xport")
body_measures = pd.read_sas("BMX_L.xpt", format="xport")
blood_pressure = pd.read_sas("BPXO_L.xpt", format="xport")

Diabetes

| Column    | Meaning                                    |
| --------- | ------------------------------------------ |
| `SEQN`    | Participant ID                             |
| `DIQ010`  | Doctor told you have diabetes              |
| `DID040`  | Age when first told you had diabetes       |
| `DIQ160`  | Ever told you have prediabetes             |
| `DIQ180`  | Had borderline diabetes                    |
| `DIQ050`  | Taking insulin now                         |
| `DID060`  | How long taking insulin                    |
| `DIQ060U` | Unit for insulin duration                  |
| `DIQ070`  | Taking diabetic pills to lower blood sugar |


For the purpose of this project we will only be using:
| Variable | Meaning                           |
| -------- | --------------------------------- |
| `DIQ010` | Told by doctor you have diabetes  |
| `DIQ160` | Told you have prediabetes         |
| `DIQ180` | Told you have borderline diabetes |

In [73]:
diabetes

,SEQN,DIQ010,DID040,DIQ160,DIQ180,DIQ050,DID060,DIQ060U,DIQ070
0,130378.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
1,130379.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN
2,130380.0,1.0,35.0,NaN,NaN,2.0,NaN,NaN,1.0
3,130381.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
11739,142306.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11740,142307.0,1.0,42.0,NaN,NaN,2.0,NaN,NaN,1.0
11741,142308.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
11742,142309.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
11743,142310.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN

In [74]:
def classify(row):
    if row["DIQ010"] == 1:
        return "diabetes"
    elif row["DIQ160"] == 1 or row["DIQ180"] == 1:
        return "borderline"
    else:
        return "none"

diabetes["target"] = diabetes.apply(classify, axis=1)
df = diabetes[["SEQN", "target"]]
df

           SEQN      target
0      130378.0        none
1      130379.0  borderline
2      130380.0    diabetes
3      130381.0        none
4      130382.0        none
...         ...         ...
11739  142306.0        none
11740  142307.0    diabetes
11741  142308.0        none
11742  142309.0        none
11743  142310.0  borderline

[11744 rows x 2 columns]

Alcohol

| Column   | Meaning                                    |
| -------- | ------------------------------------------ |
| `SEQN`   | participant ID                             |
| `ALQ111` | had at least 12 alcohol drinks in lifetime |
| `ALQ121` | drinks per year/month/week                 |
| `ALQ130` | average drinks per drinking day            |
| `ALQ142` | binge drinking frequency                   |
| `ALQ270` | heavy drinking frequency                   |
| `ALQ280` | number of drinks                           |
| `ALQ151` | drank alcohol in past year                 |
| `ALQ170` | frequency of drinking                      |


For this project we will be keeping:
| Variable | Why it’s useful                                     |
| -------- | --------------------------------------------------- |
| `ALQ151` | whether they drank in past year (baseline behavior) |
| `ALQ130` | drinks per occasion (intensity)                     |
| `ALQ170` | drinking frequency (how often)                      |

In [75]:
alcohol

,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ151,ALQ170
0,130378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,1.0,2.000000e+00,3.0,5.397605e-79,NaN,NaN,2.0,NaN
2,130380.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,2.0,NaN
3,130386.0,1.0,4.000000e+00,2.0,1.000000e+01,5.397605e-79,1.000000e+01,2.0,5.397605e-79
4,130387.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...
6332,142305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,142307.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,2.0,NaN
6334,142308.0,1.0,8.000000e+00,2.0,5.397605e-79,NaN,NaN,2.0,NaN
6335,142309.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6336,142310.0,1.0,3.000000e+00,3.0,3.000000e+00,9.000000e+00,5.397605e-79,2.0,2.000000e+00

In [76]:
alc = alcohol[[
    "SEQN",
    "ALQ151",
    "ALQ130",
    "ALQ170"
]]
alc = alc.rename(columns={
    "ALQ151": "drank_past_year",
    "ALQ130": "drinks_per_occasion",
    "ALQ170": "drinking_frequency"
})
alc

          SEQN  drank_past_year  drinks_per_occasion  drinking_frequency
0     130378.0              NaN                  NaN                 NaN
1     130379.0              2.0                  3.0                 NaN
2     130380.0              2.0                  1.0                 NaN
3     130386.0              2.0                  2.0        5.397605e-79
4     130387.0              2.0                  NaN                 NaN
...        ...              ...                  ...                 ...
6332  142305.0              NaN                  NaN                 NaN
6333  142307.0              2.0                  1.0                 NaN
6334  142308.0              2.0                  2.0                 NaN
6335  142309.0              NaN                  NaN                 NaN
6336  142310.0              2.0                  3.0        2.000000e+00

[6337 rows x 4 columns]

smoking
| Variable   | Meaning                                                                   |
| ---------- | ------------------------------------------------------------------------- |
| `SMQ020`   | Smoked at least 100 cigarettes in lifetime (ever smoker indicator)        |
| `SMQ040`   | Current smoking status (every day / some days / not at all)               |
| `SMD641`   | Age first started smoking regularly                                       |
| `SMD650`   | Number of cigarettes smoked per day                                       |
| `SMD100MN` | Time since last smoked (in months)                                        |
| `SMQ621`   | Smoking exposure / household smoking-related question (context-dependent) |
| `SMD630`   | Additional smoking history detail (often conditional on prior answers)    |
| `SMAQUEX2` | Questionnaire version / routing variable (not behavioral)                 |

For this project we chose:

| Variable | Why we include it                                                         |
| -------- | ------------------------------------------------------------------------- |
| `SMQ020` | Captures whether someone has ever been a smoker (basic exposure signal)   |
| `SMQ040` | Distinguishes current smokers from past/never smokers (behavioral status) |
| `SMD650` | Measures smoking intensity, which is strongly related to health risk      |

In [77]:
smoking

,SEQN,SMQ020,SMQ040,SMD641,SMD650,SMD100MN,SMQ621,SMD630,SMAQUEX2
0,130378.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
1,130379.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
2,130380.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,130384.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,130385.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...
9010,142305.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9011,142307.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
9012,142308.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9013,142309.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9014,142310.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0

In [78]:
smq = smoking[[
    "SEQN",
    "SMQ020",
    "SMQ040",
    "SMD650"
]]
smq = smq.rename(columns={
    "SMQ020": "ever_smoked_100_cigs",
    "SMQ040": "current_smoking_status",
    "SMD650": "cigs_per_day"
})
smq

          SEQN  ever_smoked_100_cigs  current_smoking_status  cigs_per_day
0     130378.0                   1.0                     3.0           NaN
1     130379.0                   1.0                     3.0           NaN
2     130380.0                   2.0                     NaN           NaN
3     130384.0                   2.0                     NaN           NaN
4     130385.0                   2.0                     NaN           NaN
...        ...                   ...                     ...           ...
9010  142305.0                   2.0                     NaN           NaN
9011  142307.0                   1.0                     3.0           NaN
9012  142308.0                   2.0                     NaN           NaN
9013  142309.0                   2.0                     NaN           NaN
9014  142310.0                   1.0                     3.0           NaN

[9015 rows x 4 columns]

demographics

| Variable   | Meaning                                    |
| ---------- | ------------------------------------------ |
| `SEQN`     | Participant ID (used to merge datasets)    |
| `SDDSRVYR` | Survey cycle / year group                  |
| `RIDSTATR` | Interview/exam status (2 = both completed) |
| `RIAGENDR` | Sex (1 = male, 2 = female)                 |
| `RIDAGEYR` | Age in years                               |
| `RIDAGEMN` | Age in months (used for children)          |
| `RIDRETH1` | Race/ethnicity (older coding)              |
| `RIDRETH3` | Race/ethnicity (updated coding, preferred) |
| `RIDEXMON` | Month of exam                              |
| `RIDEXAGM` | Age at exam in months (mostly for kids)    |
| `DMDHRGND` | Household reference person gender          |
| `DMDHRAGZ` | Household reference person age category    |
| `DMDHREDZ` | Education level (household ref person)     |
| `DMDHRMAZ` | Marital status (household ref person)      |
| `DMDHSEDZ` | Household education level                  |
| `WTINT2YR` | Interview sample weight                    |
| `WTMEC2YR` | Exam sample weight                         |
| `SDMVSTRA` | Stratum (survey design)                    |
| `SDMVPSU`  | PSU (survey design cluster)                |
| `INDFMPIR` | Income-to-poverty ratio                    |

For this project we will use:
| Variable   | Why |
|------------|-----|
| SEQN       | Needed to merge datasets across NHANES files |
| RIDAGEYR   | Strongest predictor; diabetes risk increases with age |
| RIAGENDR   | Sex-based differences in diabetes risk |
| RIDRETH3   | Race/ethnicity associated with population-level risk differences |
| INDFMPIR   | Income-to-poverty ratio; proxy for socioeconomic status |

In [79]:
demographics

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,12.0,2.0,1.0,9.0,NaN,2.0,2.0,1.0,111.0,...,1.0,3.0,3.0,3.0,NaN,11147.192563,13459.129019,176.0,1.0,2.01
11929,142307.0,12.0,2.0,2.0,49.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,69419.620456,64962.328962,181.0,1.0,NaN
11930,142308.0,12.0,2.0,1.0,50.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32696.313477,44367.534132,183.0,2.0,1.95
11931,142309.0,12.0,2.0,1.0,40.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,30547.974564,46249.361849,176.0,1.0,3.11
11932,142310.0,12.0,2.0,2.0,80.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32753.585494,49647.225467,187.0,2.0,5.00

In [80]:
demo = demographics[[
    "SEQN",
    "RIDAGEYR",
    "RIAGENDR",
    "RIDRETH3",
    "INDFMPIR"
]]
demo = demo.rename(columns={
    "RIDAGEYR": "age",
    "RIAGENDR": "sex",
    "RIDRETH3": "race_ethnicity",
    "INDFMPIR": "income_ratio"
})
demo

           SEQN   age  sex  race_ethnicity  income_ratio
0      130378.0  43.0  1.0             6.0          5.00
1      130379.0  66.0  1.0             3.0          5.00
2      130380.0  44.0  2.0             2.0          1.41
3      130381.0   5.0  2.0             7.0          1.53
4      130382.0   2.0  1.0             3.0          3.60
...         ...   ...  ...             ...           ...
11928  142306.0   9.0  1.0             2.0          2.01
11929  142307.0  49.0  2.0             4.0           NaN
11930  142308.0  50.0  1.0             2.0          1.95
11931  142309.0  40.0  1.0             2.0          3.11
11932  142310.0  80.0  2.0             3.0          5.00

[11933 rows x 5 columns]

physical activity

| Variable  | Meaning                                               |
| --------- | ----------------------------------------------------- |
| `SEQN`    | Participant ID                                        |
| `PAD790Q` | Moderate recreational activity frequency              |
| `PAD790U` | Unit for PAD790Q (D = days, W = weeks, M = months)    |
| `PAD800`  | Minutes of moderate recreational activity             |
| `PAD810Q` | Vigorous recreational activity frequency              |
| `PAD810U` | Unit for PAD810Q                                      |
| `PAD820`  | Minutes of vigorous activity                          |
| `PAD680`  | Total physical activity (MET-minutes / summary score) |


For this project we will use:
| Variable | Why                                    |
| -------- | -------------------------------------- |
| `PAD680` | best overall physical activity summary |
| `PAD800` | moderate activity intensity            |
| `PAD820` | vigorous activity intensity            |

In [81]:
physical_activity

,SEQN,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680
0,130378.0,3.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,360.0
1,130379.0,4.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,480.0
2,130380.0,1.000000e+00,b'W',20.0,5.397605e-79,b'',NaN,240.0
3,130384.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,60.0
4,130385.0,1.000000e+00,b'D',90.0,1.000000e+00,b'W',60.0,180.0
...,...,...,...,...,...,...,...,...
8148,142305.0,2.000000e+00,b'W',40.0,5.397605e-79,b'',NaN,480.0
8149,142307.0,3.000000e+00,b'W',15.0,5.397605e-79,b'',NaN,480.0
8150,142308.0,1.000000e+00,b'W',45.0,5.397605e-79,b'',NaN,600.0
8151,142309.0,2.000000e+00,b'D',15.0,5.397605e-79,b'',NaN,240.0
8152,142310.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,360.0

In [82]:
pa = physical_activity[[
    "SEQN",
    "PAD680",
    "PAD800",
    "PAD820"
]]
pa = pa.replace(5.397605e-79, np.nan)
pa = pa.rename(columns={
    "PAD680": "physical_activity_score",
    "PAD800": "moderate_activity_minutes",
    "PAD820": "vigorous_activity_minutes"
})
pa

,SEQN,physical_activity_score,moderate_activity_minutes,vigorous_activity_minutes
0,130378.0,360.0,45.0,45.0
1,130379.0,480.0,45.0,45.0
2,130380.0,240.0,20.0,NaN
3,130384.0,60.0,NaN,NaN
4,130385.0,180.0,90.0,60.0
...,...,...,...,...
8148,142305.0,480.0,40.0,NaN
8149,142307.0,480.0,15.0,NaN
8150,142308.0,600.0,45.0,NaN
8151,142309.0,240.0,15.0,NaN
8152,142310.0,360.0,NaN,NaN

body measure

| Variable   | Meaning                                 |
| ---------- | --------------------------------------- |
| `SEQN`     | Participant ID                          |
| `BMDSTATS` | Exam status / measurement validity flag |
| `BMXWT`    | Weight (kg)                             |
| `BMXHT`    | Height (cm)                             |
| `BMXBMI`   | Body Mass Index                         |
| `BMXWAIST` | Waist circumference                     |
| `BMXHIP`   | Hip circumference                       |
| `BMXARMC`  | Arm circumference                       |
| `BMXLEG`   | Upper leg length                        |
| `BMXARML`  | Upper arm length                        |

For this project we will use:
| Variable   | Why                                               |
| ---------- | ------------------------------------------------- |
| `BMXBMI`   | strongest single predictor of diabetes            |
| `BMXWAIST` | better indicator of visceral fat (very important) |
| `BMXWT`    | overall body mass signal                          |
| `BMXHT`    | helps contextualize weight                        |

In [83]:
body_measures

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,130378.0,1.0,86.9,NaN,NaN,NaN,NaN,NaN,179.5,NaN,...,42.8,NaN,42.0,NaN,35.7,NaN,98.3,NaN,102.9,NaN
1,130379.0,1.0,101.8,NaN,NaN,NaN,NaN,NaN,174.2,NaN,...,38.5,NaN,38.7,NaN,33.7,NaN,114.7,NaN,112.4,NaN
2,130380.0,1.0,69.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,...,38.5,NaN,35.5,NaN,36.3,NaN,93.5,NaN,98.0,NaN
3,130381.0,1.0,34.3,NaN,NaN,NaN,NaN,NaN,120.1,NaN,...,NaN,NaN,25.4,NaN,23.4,NaN,70.4,NaN,NaN,NaN
4,130382.0,3.0,13.6,NaN,NaN,1.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,1.0,25.3,NaN,NaN,NaN,NaN,NaN,128.0,NaN,...,32.0,NaN,25.0,NaN,19.0,NaN,57.7,NaN,NaN,NaN
8856,142307.0,3.0,NaN,1.0,NaN,NaN,NaN,NaN,143.8,NaN,...,NaN,1.0,34.0,NaN,35.4,NaN,NaN,1.0,NaN,1.0
8857,142308.0,1.0,79.3,NaN,NaN,NaN,NaN,NaN,173.3,NaN,...,41.8,NaN,40.0,NaN,30.6,NaN,98.4,NaN,97.7,NaN
8858,142309.0,1.0,81.9,NaN,NaN,NaN,NaN,NaN,179.1,NaN,...,44.0,NaN,40.0,NaN,30.8,NaN,96.0,NaN,103.3,NaN
8859,142310.0,1.0,72.1,NaN,NaN,NaN,NaN,NaN,161.7,NaN,...,34.2,NaN,34.0,NaN,33.5,NaN,110.8,NaN,115.0,NaN

In [84]:
bs = body_measures[[
    "SEQN",
    "BMXBMI",
    "BMXWAIST",
    "BMXWT",
    "BMXHT"
    ]]
bs = bs.rename(columns={
    "BMXBMI": "bmi",
    "BMXWAIST": "waist_measurement",
    "BMXWT": "weight",
    "BMXHT": "waist_to_height_ratio"
})
bs

          SEQN   bmi  waist_measurement  weight  waist_to_height_ratio
0     130378.0  27.0               98.3    86.9                  179.5
1     130379.0  33.5              114.7   101.8                  174.2
2     130380.0  29.7               93.5    69.4                  152.9
3     130381.0  23.8               70.4    34.3                  120.1
4     130382.0   NaN                NaN    13.6                    NaN
...        ...   ...                ...     ...                    ...
8855  142306.0  15.4               57.7    25.3                  128.0
8856  142307.0   NaN                NaN     NaN                  143.8
8857  142308.0  26.4               98.4    79.3                  173.3
8858  142309.0  25.5               96.0    81.9                  179.1
8859  142310.0  27.6              110.8    72.1                  161.7

[8860 rows x 5 columns]

blood pressure

| Variable  | Meaning                                        |
| --------- | ---------------------------------------------- |
| `SEQN`    | Participant ID                                 |
| `BPAOARM` | Arm used for measurement (R = right, L = left) |
| `BPAOCSZ` | Cuff size used (1–4 scale)                     |
| `BPXOSY1/2/3` | Systolic blood pressure (1st/2nd/3rd reading)  |
| `BPXODI1/2/3` | Diastolic blood pressure (1st/2nd/3rd reading) |

For this project we will use:
| Feature       | Meaning               |
| ------------- | --------------------- |
| systolic_avg  | average of BPXOSY1–3  |
| diastolic_avg | average of BPXODI1–3  |
| pulse_avg     | average of BPXOPLS1–3 |

In [85]:
blood_pressure

,SEQN,BPAOARM,BPAOCSZ,BPXOSY1,BPXODI1,BPXOSY2,BPXODI2,BPXOSY3,BPXODI3,BPXOPLS1,BPXOPLS2,BPXOPLS3
0,130378.0,b'R',4.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0
1,130379.0,b'R',4.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0
2,130380.0,b'R',4.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0
3,130386.0,b'R',4.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0
4,130387.0,b'R',4.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7796,142306.0,b'R',2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7797,142307.0,b'R',4.0,127.0,75.0,132.0,73.0,131.0,72.0,71.0,70.0,67.0
7798,142308.0,b'R',3.0,106.0,65.0,106.0,69.0,112.0,74.0,58.0,61.0,69.0
7799,142309.0,b'R',3.0,127.0,81.0,125.0,82.0,128.0,81.0,80.0,79.0,83.0
7800,142310.0,b'R',4.0,128.0,81.0,121.0,78.0,129.0,81.0,77.0,78.0,79.0

In [86]:
blood_pressure["systolic"] = blood_pressure[["BPXOSY1","BPXOSY2","BPXOSY3"]].mean(axis=1)
blood_pressure["diastolic"] = blood_pressure[["BPXODI1","BPXODI2","BPXODI3"]].mean(axis=1)
blood_pressure["pulse"] = blood_pressure[["BPXOPLS1","BPXOPLS2","BPXOPLS3"]].mean(axis=1)

bp = blood_pressure[["SEQN", "systolic", "diastolic", "pulse"]]
bp

          SEQN    systolic  diastolic      pulse
0     130378.0  132.666667  96.000000  81.000000
1     130379.0  117.000000  78.666667  72.000000
2     130380.0  109.000000  78.333333  81.333333
3     130386.0  115.000000  73.666667  62.333333
4     130387.0  141.333333  76.000000  79.000000
...        ...         ...        ...        ...
7796  142306.0         NaN        NaN        NaN
7797  142307.0  130.000000  73.333333  69.333333
7798  142308.0  108.000000  69.333333  62.666667
7799  142309.0  126.666667  81.333333  80.666667
7800  142310.0  126.000000  80.000000  78.000000

[7801 rows x 4 columns]

Merging

In [87]:
df = df.merge(demo, on="SEQN", how="left")
df = df.merge(alc, on="SEQN", how="left")
df = df.merge(smq, on="SEQN", how="left")
df = df.merge(pa, on="SEQN", how="left")
df = df.merge(bs, on="SEQN", how="left")
df = df.merge(bp, on="SEQN", how="left")
df

,SEQN,target,age,sex,race_ethnicity,income_ratio,drank_past_year,drinks_per_occasion,drinking_frequency,ever_smoked_100_cigs,...,physical_activity_score,moderate_activity_minutes,vigorous_activity_minutes,bmi,waist_measurement,weight,waist_to_height_ratio,systolic,diastolic,pulse
0,130378.0,none,43.0,1.0,6.0,5.00,NaN,NaN,NaN,1.0,...,360.0,45.0,45.0,27.0,98.3,86.9,179.5,132.666667,96.000000,81.000000
1,130379.0,borderline,66.0,1.0,3.0,5.00,2.0,3.0,NaN,1.0,...,480.0,45.0,45.0,33.5,114.7,101.8,174.2,117.000000,78.666667,72.000000
2,130380.0,diabetes,44.0,2.0,2.0,1.41,2.0,1.0,NaN,2.0,...,240.0,20.0,NaN,29.7,93.5,69.4,152.9,109.000000,78.333333,81.333333
3,130381.0,none,5.0,2.0,7.0,1.53,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,23.8,70.4,34.3,120.1,NaN,NaN,NaN
4,130382.0,none,2.0,1.0,3.0,3.60,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13.6,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11739,142306.0,none,9.0,1.0,2.0,2.01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,15.4,57.7,25.3,128.0,NaN,NaN,NaN
11740,142307.0,diabetes,49.0,2.0,4.0,NaN,2.0,1.0,NaN,1.0,...,480.0,15.0,NaN,NaN,NaN,NaN,143.8,130.000000,73.333333,69.333333
11741,142308.0,none,50.0,1.0,2.0,1.95,2.0,2.0,NaN,2.0,...,600.0,45.0,NaN,26.4,98.4,79.3,173.3,108.000000,69.333333,62.666667
11742,142309.0,none,40.0,1.0,2.0,3.11,NaN,NaN,NaN,2.0,...,240.0,15.0,NaN,25.5,96.0,81.9,179.1,126.666667,81.333333,80.666667
11743,142310.0,borderline,80.0,2.0,3.0,5.00,2.0,3.0,2.0,1.0,...,360.0,NaN,NaN,27.6,110.8,72.1,161.7,126.000000,80.000000,78.000000